import type { Store } from "./types";

export const SEED_STORES: Store[] = [
  {
    id: "anaka",
    name: "متجر الأناقة الجزائرية",
    owner: "أمين بلال",
    phone: "213775554695",
    email: "merada35@gmail.com",
    wilaya: "16",
    category: "fashion",
    seed: true,
    active: true,
    products: [
      {
        id: "watch-noria",
        title: "ساعة يد مقاومة للماء",
        price: 6500,
        desc: "ساعة يومية بإطار معدني هادئ، مقاومة للماء، مع ضمان سنة وتوصيل داخل الولايات.",
        art: "watch",
        imageUrl: "",
        stock: 10,
        category: "fashion",
        featured: true,
        active: true,
      },
      {
        id: "bag-casbah",
        title: "حقيبة ظهر جلد عملي",
        price: 4800,
        desc: "حقيبة تتسع لحاسوب محمول صغير، بطانات داخلية، مناسبة للعمل والتنقل اليومي.",
        art: "bag",
        imageUrl: "",
        stock: 5,
        category: "fashion",
        featured: true,
        active: true,
      },
      {
        id: "scarf-tell",
        title: "وشاح قطن منسوج",
        price: 2200,
        desc: "وشاح خفيف بنسيج هادئ، يناسب الربيع والخريف، متوفر بلون حبر وورق.",
        art: "scarf",
        imageUrl: "",
        stock: 18,
        category: "fashion",
        featured: false,
        active: true,
      },
    ],
  },
  {
    id: "tactic",
    name: "تكتيك للإلكترونيات",
    owner: "كمال الدين",
    phone: "213660000000",
    email: "tactic@store.dz",
    wilaya: "31",
    category: "electronics",
    seed: true,
    active: true,
    products: [
      {
        id: "buds-clear",
        title: "سماعات لاسلكية عازلة",
        price: 3200,
        desc: "بطارية طويلة وعزل جيد للضجيج، مناسبة للمكالمات والتنقل داخل المدينة.",
        art: "headphones",
        imageUrl: "",
        stock: 15,
        category: "electronics",
        featured: true,
        active: true,
      },
      {
        id: "bank-day",
        title: "شاحن متنقل سريع",
        price: 4100,
        desc: "سعة تكفي لشحن الهاتف أكثر من مرة، منفذين، جسم مدمج للجيب.",
        art: "powerbank",
        imageUrl: "",
        stock: 12,
        category: "electronics",
        featured: true,
        active: true,
      },
      {
        id: "lamp-desk",
        title: "مصباح مكتب قابل للطي",
        price: 2900,
        desc: "إضاءة هادئة للعمل الليلي، ذراع مرن، يستهلك طاقة منخفضة.",
        art: "lamp",
        imageUrl: "",
        stock: 9,
        category: "home",
        featured: false,
        active: true,
      },
    ],
  },
  {
    id: "qahwa",
    name: "دار البن والبهارات",
    owner: "ليلى بن عمر",
    phone: "213555000000",
    email: "qahwa@store.dz",
    wilaya: "16",
    category: "food",
    seed: true,
    active: true,
    products: [
      {
        id: "coffee-tell",
        title: "بن محمص تحميص متوسط",
        price: 1800,
        desc: "كيلو بن محمص للأباريق المنزلية، نكهة متوازنة بدون مرارة زائدة.",
        art: "coffee",
        imageUrl: "",
        stock: 24,
        category: "food",
        featured: true,
        active: true,
      },
      {
        id: "spice-mix",
        title: "خلطة بهارات الكسكس",
        price: 950,
        desc: "خلطة جاهزة بوزن 250غ، معبأة بإحكام، مناسبة للقدر العائلي.",
        art: "spices",
        imageUrl: "",
        stock: 30,
        category: "food",
        featured: false,
        active: true,
      },
    ],
  },
];
