export const WILAYAS: { code: string; name: string }[] = [
  { code: "16", name: "الجزائر" },
  { code: "31", name: "وهران" },
  { code: "25", name: "قسنطينة" },
  { code: "09", name: "البليدة" },
  { code: "19", name: "سطيف" },
  { code: "06", name: "بجاية" },
  { code: "15", name: "تيزي وزو" },
  { code: "23", name: "عنابة" },
  { code: "05", name: "باتنة" },
  { code: "13", name: "تلمسان" },
  { code: "27", name: "مستغانم" },
  { code: "26", name: "المدية" },
  { code: "17", name: "الجلفة" },
  { code: "21", name: "سكيكدة" },
  { code: "02", name: "الشلف" },
  { code: "04", name: "أم البواقي" },
  { code: "07", name: "بسكرة" },
  { code: "08", name: "بشار" },
  { code: "10", name: "البويرة" },
  { code: "12", name: "تبسة" },
  { code: "14", name: "تيارت" },
  { code: "18", name: "جيجل" },
  { code: "20", name: "سعيدة" },
  { code: "22", name: "سيدي بلعباس" },
  { code: "24", name: "قالمة" },
  { code: "28", name: "المسيلة" },
  { code: "29", name: "معسكر" },
  { code: "30", name: "ورقلة" },
  { code: "34", name: "برج بوعريريج" },
  { code: "35", name: "بومرداس" },
  { code: "42", name: "تيبازة" },
  { code: "44", name: "عين الدفلى" },
  { code: "47", name: "غرداية" },
  { code: "01", name: "أدرار" },
  { code: "03", name: "الأغواط" },
  { code: "11", name: "تمنراست" },
  { code: "32", name: "البيض" },
  { code: "33", name: "إليزي" },
  { code: "36", name: "الطارف" },
  { code: "37", name: "تندوف" },
  { code: "38", name: "تيسمسيلت" },
  { code: "39", name: "الوادي" },
  { code: "40", name: "خنشلة" },
  { code: "41", name: "سوق أهراس" },
  { code: "43", name: "ميلة" },
  { code: "45", name: "النعامة" },
  { code: "46", name: "عين تموشنت" },
  { code: "48", name: "غليزان" },
  { code: "49", name: "تيميمون" },
  { code: "50", name: "برج باجي مختار" },
  { code: "51", name: "أولاد جلال" },
  { code: "52", name: "بني عباس" },
  { code: "53", name: "عين صالح" },
  { code: "54", name: "عين قزام" },
  { code: "55", name: "تقرت" },
  { code: "56", name: "جانت" },
  { code: "57", name: "المغير" },
  { code: "58", name: "المنيعة" },
];

export function wilayaName(code: string): string {
  if (code === "all") return "كل الولايات";
  return WILAYAS.find((w) => w.code === code)?.name ?? code;
}
