/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresStoreIdRouteImport } from './routes/stores.$storeId'
import { Route as PStoreIdProductIdRouteImport } from './routes/p.$storeId.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoresRoute,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => StoresRoute,
} as any)
const PStoreIdProductIdRoute = PStoreIdProductIdRouteImport.update({
  id: '/p/$storeId/$productId',
  path: '/p/$storeId/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merchant': typeof MerchantRoute
  '/stores': typeof StoresRouteWithChildren
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/': typeof StoresIndexRoute
  '/p/$storeId/$productId': typeof PStoreIdProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merchant': typeof MerchantRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores': typeof StoresIndexRoute
  '/p/$storeId/$productId': typeof PStoreIdProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merchant': typeof MerchantRoute
  '/stores': typeof StoresRouteWithChildren
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/': typeof StoresIndexRoute
  '/p/$storeId/$productId': typeof PStoreIdProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/merchant'
    | '/stores'
    | '/stores/$storeId'
    | '/stores/'
    | '/p/$storeId/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/merchant'
    | '/stores/$storeId'
    | '/stores'
    | '/p/$storeId/$productId'
  id:
    | '__root__'
    | '/'
    | '/merchant'
    | '/stores'
    | '/stores/$storeId'
    | '/stores/'
    | '/p/$storeId/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerchantRoute: typeof MerchantRoute
  StoresRoute: typeof StoresRouteWithChildren
  PStoreIdProductIdRoute: typeof PStoreIdProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof StoresRoute
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof StoresRoute
    }
    '/p/$storeId/$productId': {
      id: '/p/$storeId/$productId'
      path: '/p/$storeId/$productId'
      fullPath: '/p/$storeId/$productId'
      preLoaderRoute: typeof PStoreIdProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoresRouteChildren {
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  StoresIndexRoute: typeof StoresIndexRoute
}

const StoresRouteChildren: StoresRouteChildren = {
  StoresStoreIdRoute: StoresStoreIdRoute,
  StoresIndexRoute: StoresIndexRoute,
}

const StoresRouteWithChildren =
  StoresRoute._addFileChildren(StoresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerchantRoute: MerchantRoute,
  StoresRoute: StoresRouteWithChildren,
  PStoreIdProductIdRoute: PStoreIdProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
